# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399952d92d1ab91615edd5c8e59b8db4570065638011689838553882f06d35af94a9e5a4ba189a26d015efa3647f5e793f5f07dd3dc5d60c61caa6d7fcdc4060

test:
  secret_key_base: 3a49118af385513da46d9145a2075e7ea90390a7a7cb441c07e984d10112dadb766ee90929fef62b684a903563af5566b07bea49c6d7e9b573dcf8f361d2661c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
